controller_list:
- name: arm_controller
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
      - panda_joint8
- name: hand_controller
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
      - panda_finger_joint1
      - panda_finger_joint2
initial:
  - group: panda_arm_hand
    pose: ready
#I added the next following lines to see if it would generate a good result
  - group: hand
    pose: open
  - group: panda_arm
    pose: start